=== claudefauconnet/devisu/deVisu2c/WebContent/pot/data/radar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcmitype="http://purl.org/dc/dcmitype/"
	targetNamespace="http://purl.org/dc/terms/" xmlns="http://purl.org/dc/terms/"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

<xs:element name="radars" type="_radars" />
	<xs:complexType name="_radars">
		<xs:sequence>
				<xs:element name="technologies" type="_radar" maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	

	<xs:complexType name="_radar" mixed="true">
		<xs:sequence>
			<xs:element type="_aclType" name="acl" maxOccurs="unbounded"
				minOccurs="0" />
			<xs:element type="_field" name="field" minOccurs="1"
				maxOccurs="unbounded" />
			<xs:element type="_background" name="background"
				maxOccurs="1" minOccurs="0" />
			<xs:element type="xs:string" name="foreignKey" maxOccurs="unbounded"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" use="required"></xs:attribute>
		<xs:attribute type="xs:string" name="title" use="required"></xs:attribute>
		<xs:attribute type="xs:string" name="dbName" use="optional"></xs:attribute>
		<xs:attribute type="xs:string" name="collectionName" use="optional"></xs:attribute>
		<xs:attribute type="xs:string" name="background-image"
			use="optional"></xs:attribute>
		<xs:attribute type="xs:string" name="infosPage" use="optional"></xs:attribute>
		<xs:attribute type="xs:string" name="displayType" use="optional"></xs:attribute>
		<xs:attribute type="xs:string" name="leftColor" use="optional"></xs:attribute>
		<xs:attribute type="xs:string" name="rightColor" use="optional"></xs:attribute>
		<xs:attribute type="xs:string" name="multiValuedFieldSep"
			use="required"></xs:attribute>

	</xs:complexType>


	<xs:complexType name="_background">
		<xs:attribute type="xs:string" name="start-color" use="required"></xs:attribute>
		<xs:attribute type="xs:string" name="end-color" use="required"></xs:attribute>
		<xs:attribute type="xs:integer" name="number-horizontal-steps"
			use="required"></xs:attribute>
		<xs:attribute type="xs:integer" name="number-radial-steps"
			use="required"></xs:attribute>
		<xs:attribute type="_backgroundOrder" name="order-horizontal-steps"
			use="optional"></xs:attribute>
		<xs:attribute type="_backgroundOrder" name="order-radial-steps"
			use="optional"></xs:attribute>
		<xs:attribute type="_backgroundType" name="type" use="required"></xs:attribute>
	</xs:complexType>


	<xs:simpleType name="_backgroundType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="radial" />
			<xs:enumeration value="cartesian" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_backgroundOrder">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ascendant" />
			<xs:enumeration value="descendant" />
		</xs:restriction>
	</xs:simpleType>



	<xs:complexType name="_field" mixed="true">
		<xs:sequence>
			<xs:element type="_enumType" name="enum" maxOccurs="unbounded"
				minOccurs="0" />
			<xs:element type="xs:string" name="linkUrlPreffix"
				maxOccurs="1" minOccurs="0" />
			<xs:element type="_aclType" name="acl" maxOccurs="unbounded"
				minOccurs="0" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" use="required"></xs:attribute>
		<xs:attribute type="_fieldType" name="type" use="required"></xs:attribute>
		<xs:attribute type="xs:boolean" name="mandatory" use="optional"></xs:attribute>
		<xs:attribute type="_radarRole" name="radarRole" use="optional"></xs:attribute>
		<xs:attribute type="xs:boolean" name="isFilter" default="true"
			use="optional"></xs:attribute>
		<xs:attribute type="xs:boolean" name="isMultivalued"
			default="false" use="optional"></xs:attribute>
		<xs:attribute type="xs:boolean" name="displayInDetailsPage"
			default="true" use="optional"></xs:attribute>
	</xs:complexType>


	<xs:complexType name="_enumType">
		<xs:attribute type="xs:string" name="label" use="required"></xs:attribute>
		<xs:attribute type="_enumShapeType" name="shape" default="circle"></xs:attribute>
		<xs:attribute type="xs:string" name="color" use="optional"></xs:attribute>
		<xs:attribute type="xs:string" name="size" use="optional"></xs:attribute>
		<xs:attribute type="xs:string" name="width" use="optional"></xs:attribute>
		<xs:attribute type="xs:string" name="height" use="optional"></xs:attribute>
		<xs:attribute type="xs:string" name="symbol" use="optional"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="_aclType">
		<xs:attribute type="xs:string" name="groupName" use="required"></xs:attribute>
		<xs:attribute type="_enumRightType" name="right" use="required"></xs:attribute>
	</xs:complexType>


	<xs:simpleType name="_enumRightType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="none" />
			<xs:enumeration value="read" />
			<xs:enumeration value="write" />
			<xs:enumeration value="admin" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_fieldType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="id" />
			<xs:enumeration value="string" />
			<xs:enumeration value="number" />
			<xs:enumeration value="enum" />
			<xs:enumeration value="date" />
			<xs:enumeration value="text" />
			<xs:enumeration value="richText" />
			<xs:enumeration value="link" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_radarRole">
		<xs:restriction base="xs:string">
			<xs:enumeration value="" />
			<xs:enumeration value="id" />
			<xs:enumeration value="x" />
			<xs:enumeration value="y" />
			<xs:enumeration value="horizontalAxis" />
			<xs:enumeration value="radialAxis" />
			<xs:enumeration value="label" />
			<xs:enumeration value="color" />
			<xs:enumeration value="symbol" />
			<xs:enumeration value="size" />
			<xs:enumeration value="shape" />
			<xs:enumeration value="comment" />
			<xs:enumeration value="link" />
			<xs:enumeration value="other" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="_enumShapeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="circle" />
			<xs:enumeration value="square" />
			<xs:enumeration value="triangleUp" />
			<xs:enumeration value="triangleDown" />
			<xs:enumeration value="textBox" />
		</xs:restriction>
	</xs:simpleType>







</xs:schema>

=== claudefauconnet/devisu/deVisu2c/WebContent/pot/data/DigitalPortfolio.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<radars xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://purl.org/dc/terms/ radar.xsd ">
	<radar multiValuedFieldSep="," name="DigitalPortfolio">

		<field mandatory="true" name="id" radarRole="id" type="id" />
		<field mandatory="true" name="x" radarRole="x" type="number" />
		<field mandatory="true" name="y" radarRole="y" type="number" />
		
		
		

			<field name="name" radarRole="label" isFilter="true" />
				<field name="ImportanceDigital" radarRole="horizontalAxis" isFilter="true" />
			<field name="ImportanceManagement" radarRole="radialAxis" isFilter="true" />


			<field name="MeteoProjet" radarRole="color">
				<enum color="#AA3939" label="0" />
				<enum color="#2D882D" label="1" />
			</field>
		<field name="MeteoProjet"  isFilter="true" />
			<field name="domain"  isFilter="true" />
			<field name="Division"  isFilter="true" />
			<field name="Sector"  isFilter="true" />
			<field name="Business"  isFilter="true" />
			<field name="Segmentation"  isFilter="true" />
			<field name="Location"  isFilter="true" />

		<background xmlns="http://purl.org/dc/terms/" start-color="#C9B5FF"
			end-color="#F0F7FF" number-horizontal-steps="3" number-radial-steps="3"
			type="cartesian" order-horizontal-steps="ascendant" order-radial-steps="ascendant" />
	
	</radar>


	<radar multiValuedFieldSep="," name="POTuseCases">

		<field mandatory="true" name="id" radarRole="id" type="id" />
		<field mandatory="true" name="x" radarRole="x" type="number" />
		<field mandatory="true" name="y" radarRole="y" type="number" />
		<field name="bu" isFilter="true">
			<field name="year" isFilter="true" />
			<field name="BD" isFilter="true" />
			<field name="BC" isFilter="true" />


			<field name="name" radarRole="label" isFilter="true" />


			<field name="maturity" radarRole="horizontalAxis" isFilter="true" />
			<field name="value" radarRole="radialAxis" isFilter="true" />


		<field name="impact" radarRole="color">
				<enum color="#7A7087" label="traditionnal" />
				<enum color="#C70821" label="disruptive" />
				<enum color="#FCAB08" label="transformationnal" />
				
			</field>
			
				<!--<field name="impact" radarRole="color">
				<enum color="#0000ee" label="traditionnal" />
				<enum color="#277554" label="disruptive" />
				<enum color="#FCAB08" label="transformationnal" />
				
			</field>-->
			
			<field name="maturity" radarRole="size">
			
				<enum label="emerging" size="6" />
				<enum label="adolescent" size="10" />
				<enum label="first rollout" size="14" />
				<enum label="mainstream" size="18" />
			</field>
			


			<!-- <field isMultivalued="true" name="Domaine" isFilter="true"/> <field 
				isMultivalued="true" name="activity" isFilter="true"/> -->

		</field>

		
		<foreignKey>detail_id</foreignKey>
	</radar>
</radars>

=== claudefauconnet/devisu/deVisu2c/WebContent/pot/data/POT2016.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<radars xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://purl.org/dc/terms/ radar.xsd ">
	<radar multiValuedFieldSep="," name="Technologies" dbName="POT2016"
		collectionName="technologies" infosPage="infosTechno.html">
		<field mandatory="true" name="id" radarRole="id" type="id" />
		<field mandatory="true" name="x" radarRole="x" type="number" />
		<field mandatory="true" name="y" radarRole="y" type="number" />
		<field name="bu" isFilter="true">
			<field name="year" isFilter="true" />
			<field name="version" isFilter="true" />

			<field name="type" isFilter="true" />
			<field name="category" isFilter="true" />
			<field name="level" isFilter="true" />
			<field name="name" radarRole="label" isFilter="true" />


			<field name="digitalPolarity" radarRole="horizontalAxis"
				isFilter="true" />
			<field name="technologyMaturity" radarRole="radialAxis"
				isFilter="true" />




			<field name="category" radarRole="color">
				<enum color="#C70821" label="Data/info valorization" />
				<enum color="#2C9E03" label="Physical world representation" />
				<enum color="#FCAB08" label="Physical world" />
				<enum color="#5A5AEE" label="Communication / social" />
				<enum color="#AABBCC" label="IT means" />



			</field>
			<field name="marketSkills" radarRole="size">
				<enum label="1" size="6" />
				<enum label="2" size="10" />
				<enum label="3" size="14" />
			</field>

			<!-- <field name="type" radarRole="shape"> <enum label="practice" shape="square" 
				/> <enum label="technology" shape="circle" /> </field> -->

			<!-- <field isMultivalued="true" name="Domaine" isFilter="true"/> <field 
				isMultivalued="true" name="activity" isFilter="true"/> -->

		</field>

		<!--<field name="excluded" radarRole="other" /> -->

		<background xmlns="http://purl.org/dc/terms/" start-color="#C9B5FF"
			end-color="#F0F7FF" number-horizontal-steps="5" number-radial-steps="4"
			type="cartesian" order-horizontal-steps="ascendant"
			order-radial-steps="descendant" />
		<foreignKey>detail_id</foreignKey>
	</radar>





	<radar multiValuedFieldSep="," name="UseCases" dbName="POT2016"
		collectionName="use_cases" infosPage="infosUseCase.html">
		>

		<field mandatory="true" name="id" radarRole="id" type="id" />
		<field mandatory="true" name="x" radarRole="x" type="number" />
		<field mandatory="true" name="y" radarRole="y" type="number" />
		<field name="bu" isFilter="true">
			<field name="year" isFilter="true" />
			<field name="BD" isFilter="true" />
			<field name="BC" isFilter="true" />
			<field name="priority" isFilter="true" />

			<field name="name" radarRole="label" isFilter="true" />
			<field name="horizon" radarRole="horizontalAxis" isFilter="true" />
			<field name="businessValue" radarRole="radialAxis" isFilter="true" />


			<field name="riskLevel" radarRole="color">
				<enum color="green" label="1" />
				<enum color="yellow" label="2" />
				<enum color="red" label="3" />

			</field>

			<!--<field name="impact" radarRole="color"> <enum color="#0000ee" label="traditionnal" 
				/> <enum color="#277554" label="disruptive" /> <enum color="#FCAB08" label="transformationnal" 
				/> </field> -->

			<field name="easeOfImpl" radarRole="size">
				<enum label="3" size="6" />
				<enum label="2" size="10" />
				<enum label="1" size="14" />


			</field>



			<!-- <field isMultivalued="true" name="Domaine" isFilter="true"/> <field 
				isMultivalued="true" name="activity" isFilter="true"/> -->

		</field>


		<background xmlns="http://purl.org/dc/terms/" start-color="#C9B5FF"
			end-color="#F0F7FF" number-horizontal-steps="3" number-radial-steps="3"
			type="radial" order-horizontal-steps="ascendant" order-radial-steps="ascendant" />
		<foreignKey>detail_id</foreignKey>
	</radar>






	<radar multiValuedFieldSep="," name="ScenariosArch" displayType="textBox"
		dbName="POT2016" collectionName="buildingBlocks" infosPage="infosScenarioArch.html"
		background-image="data/archMap.png">

		<field mandatory="true" name="id" radarRole="id" type="id" />
		<field mandatory="true" name="x" radarRole="x" type="number" />
		<field mandatory="true" name="y" radarRole="y" type="number" />
		<field name="Layer" isFilter="true" />
		<field name="layer_index" isFilter="true" />



		<field name="name" radarRole="label" isFilter="true" />


		<field name="XXX" radarRole="horizontalAxis" />
		<field name="YYY" radarRole="radialAxis" />


		<field name="maturity" radarRole="color" isFilter="true">
			<enum color="#efe" label="innovative" />
			<enum color="#fee" label="main Stream" />
			<enum color="white" label="layer" />

		</field>



		<background xmlns="http://purl.org/dc/terms/" start-color="#ffeeff"
			end-color="#ffeeff" number-horizontal-steps="2" number-radial-steps="1"
			type="cartesian" order-horizontal-steps="ascendant"
			order-radial-steps="ascendant" />

		<!-- <background xmlns="http://purl.org/dc/terms/" start-color="#C9B5FF" 
			end-color="#F0F7FF" number-horizontal-steps="1" number-radial-steps="7" type="cartesian" 
			order-horizontal-steps="ascendant" order-radial-steps="ascendant" / -->


		<foreignKey>detail_id</foreignKey>
	</radar>

	<radar multiValuedFieldSep="," name="ScenariosRadar" dbName="POT2016"
		collectionName="scenarios" infosPage="infosScenario.html">
		
		<field name="name" radarRole="label" isFilter="true" />
		<field mandatory="true" name="id" radarRole="id" type="id" />
		<field mandatory="true" name="x" radarRole="x" type="number" />
		<field mandatory="true" name="y" radarRole="y" type="number" />
		
		<field name="category" isFilter="true" />
		<field name="horizon" isFilter="true" />
		<field name="riskLevel" isFilter="true" />
		<field name="maturity" isFilter="true" />
		<field name="costLevel" isFilter="true" />
		<field name="marketSkills" isFilter="true" />
		<field name="orgSkills" isFilter="true" />


		<field name="easeOfImpl" radarRole="horizontalAxis" isFilter="true" />
		<field name="businessValue" radarRole="radialAxis" isFilter="true" />


		<field name="maturity" radarRole="color">
			<enum color="#7A7087" label="1" />
			<enum color="#C70821" label="2" />
			<enum color="#FCAB08" label="3" />

		</field>

		<!--<field name="impact" radarRole="color"> <enum color="#0000ee" label="traditionnal" 
			/> <enum color="#277554" label="disruptive" /> <enum color="#FCAB08" label="transformationnal" 
			/> </field> -->

		<field name="maturity" radarRole="size">
			<enum label="1" size="6" />
			<enum label="2" size="10" />
			<enum label="3" size="14" />


		</field>



		<!-- <field isMultivalued="true" name="Domaine" isFilter="true"/> <field 
			isMultivalued="true" name="activity" isFilter="true"/> -->

	


		<background xmlns="http://purl.org/dc/terms/" start-color="#C9B5FF"
			end-color="#F0F7FF" number-horizontal-steps="2" number-radial-steps="2"
			type="cartesian" order-horizontal-steps="ascendant"
			order-radial-steps="ascendant" />
		<foreignKey>detail_id</foreignKey>
	</radar>
</radars>

=== claudefauconnet/devisu/deVisu2c/WebContent/pot/data/POT.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<radars xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://purl.org/dc/terms/ radar.xsd ">
	<radar multiValuedFieldSep="," name="POT">

		<field mandatory="true" name="id" radarRole="id" type="id" />
		<field mandatory="true" name="x" radarRole="x" type="number" />
		<field mandatory="true" name="y" radarRole="y" type="number" />
		<field name="bu" isFilter="true">
			<field name="year" isFilter="true" />
			<field name="version" isFilter="true" />

			<field name="type" isFilter="true" />
			<field name="level" isFilter="true" />
		

			<field name="techno" radarRole="label" isFilter="true" />
			<field name="details_id" isFilter="true" />

			<field name="availability" radarRole="horizontalAxis" isFilter="true" />
			<field name="businessValue" radarRole="radialAxis" isFilter="true" />


			<field name="maturity" radarRole="color">
				<enum color="#eee" label="no interet" />
				<enum color="#C70821" label="emerging" />
				<enum color="#FCAB08" label="adolescent" />
				<enum color="#2C9E03" label="first rollout" />
				<enum color="#7A7087" label="mainstream" />
			</field>
			<field name="priority" radarRole="size">
				<enum label="low" size="6" />
				<enum label="medium" size="10" />
				<enum label="high" size="14" />
			</field>

			<field name="type" radarRole="shape">
				<enum label="practice" shape="square" />
				<enum label="technology" shape="circle" />
			</field>

			<!-- <field isMultivalued="true" name="Domaine" isFilter="true"/> <field 
				isMultivalued="true" name="activity" isFilter="true"/> -->

		</field>
		
			<field name="excluded" radarRole="other" />

		<background xmlns="http://purl.org/dc/terms/" start-color="#C9B5FF"
			end-color="#F0F7FF" number-horizontal-steps="3" number-radial-steps="3"
			type="radial" order-horizontal-steps="ascendant" order-radial-steps="ascendant" />
		<foreignKey>detail_id</foreignKey>
	</radar>


	<radar multiValuedFieldSep="," name="POTuseCases">

		<field mandatory="true" name="id" radarRole="id" type="id" />
		<field mandatory="true" name="x" radarRole="x" type="number" />
		<field mandatory="true" name="y" radarRole="y" type="number" />
		<field name="bu" isFilter="true">
			<field name="year" isFilter="true" />
			<field name="BD" isFilter="true" />
			<field name="BC" isFilter="true" />


			<field name="name" radarRole="label" isFilter="true" />


			<field name="maturity" radarRole="horizontalAxis" isFilter="true" />
			<field name="value" radarRole="radialAxis" isFilter="true" />


		<field name="impact" radarRole="color">
				<enum color="#7A7087" label="traditionnal" />
				<enum color="#C70821" label="disruptive" />
				<enum color="#FCAB08" label="transformationnal" />
				
			</field>
			
				<!--<field name="impact" radarRole="color">
				<enum color="#0000ee" label="traditionnal" />
				<enum color="#277554" label="disruptive" />
				<enum color="#FCAB08" label="transformationnal" />
				
			</field>-->
			
			<field name="maturity" radarRole="size">
				<enum label="emerging" size="6" />
				<enum label="adolescent" size="10" />
				<enum label="first rollout" size="14" />
				<enum label="mainstream" size="18" />
			</field>
			


			<!-- <field isMultivalued="true" name="Domaine" isFilter="true"/> <field 
				isMultivalued="true" name="activity" isFilter="true"/> -->

		</field>

		<background xmlns="http://purl.org/dc/terms/" start-color="#C9B5FF"
			end-color="#F0F7FF" number-horizontal-steps="3" number-radial-steps="3"
			type="radial" order-horizontal-steps="ascendant" order-radial-steps="ascendant" />
		<foreignKey>detail_id</foreignKey>
	</radar>
</radars>
